instrumentation:
  root: ./src
  include-all-sources: true
  compact: false
  preserve-comments: true
  complete-copy: true
check:
  global:
    statements: 100
    lines: 100
    functions: 100
    branches: 100

